num1=int(input('digite um numero'))
print ('-'*12)
print('multiplicado por 1  =', (num1*1))
print('multiplicado por 2  =', (num1*2))
print('multiplicado por 3  =', (num1*3))
print('multiplicado por 4  =', (num1*4))
print('multiplicado por 5  =', (num1*5))
print('multiplicado por 6  =', (num1*6))
print('multiplicado por 7  =', (num1*7))
print('multiplicado por 8  =', (num1*8))
print('multiplicado por 9  =', (num1*9))
print('multiplicado por 10 =', (num1*10))
print ('-'*12)
